db_conn: sqlite3://database/vuln_v3.sqlite3
interval: 30m
enable_cve_filter: true
no_github_search: false
no_start_message: false
diff_mode: false
white_keywords: [ ]
black_keywords: [ ]

pusher:
  - type: lark
    access_token: ""
    sign_secret: ""