# Generated by Django 5.1.4 on 2025-01-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='唯一标识符', max_length=100, unique=True)),
                ('title', models.CharField(help_text='漏洞标题', max_length=255)),
                ('description', models.TextField(help_text='漏洞描述')),
                ('severity', models.CharField(choices=[('低', '低'), ('中', '中'), ('高', '高'), ('严重', '严重')], help_text='漏洞严重性', max_length=10)),
                ('cve', models.CharField(blank=True, help_text='CVE编号', max_length=50, null=True)),
                ('disclosure', models.DateField(blank=True, help_text='披露日期', null=True)),
                ('solutions', models.TextField(blank=True, help_text='解决方案', null=True)),
                ('references', models.JSONField(blank=True, help_text='参考链接列表', null=True)),
                ('tags', models.CharField(blank=True, help_text='标签，逗号分隔', max_length=255, null=True)),
                ('github_search', models.URLField(blank=True, help_text='GitHub搜索链接', null=True)),
                ('source', models.CharField(blank=True, help_text='漏洞来源', max_length=255, null=True)),
                ('pushed', models.BooleanField(default=False, help_text='是否已推送')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间')),
            ],
            options={
                'verbose_name': '漏洞信息',
                'verbose_name_plural': '漏洞信息',
                'db_table': 'vuln_informations',
                'managed': False,
            },
        ),
    ]
